# Indexing & Slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (lists)

In [60]:
import numpy as np
import pandas as pd

from IPython.display import Image 
from IPython.core.display import HTML  # For adding images to this notebook



## Indexing

In [11]:
a = np.arange(10)

print (a) # print them all out, 10 is not shows because Python Indices ALWAYS starts with ZERO

a[0], a[2], a[-1]

[0 1 2 3 4 5 6 7 8 9]


(0, 2, 9)

In [25]:
a = np.diag(np.arange(3))

print (a) # I OVERLY USE PRINT STATEMENTS ON PURPOSE

print (a[1, 1])

a[2, 1] = 10  # Add a '10' to the 3rd row, 2nd column 

a[1, 1] = 4

print (a)

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[[ 0  0  0]
 [ 0  4  0]
 [ 0 10  2]]


## Slicing

In [69]:
a = np.arange(10)
print (a)



# Play around with slicing, what does it do? Use Negative numbers!

# Remove the # in order to view what each print statement does.
#print (a[2:9:3]) # [Start:end:step]
#print (a[:5])
#print (a[2])
#print (a[2:9:1])
#print (a[-2:])

[0 1 2 3 4 5 6 7 8 9]


## This is a cool illustration of Numpy Indexing & Slicing

In [61]:

Image(url= "http://www.scipy-lectures.org/_images/numpy_indexing.png")

# Copies & Views

A slicing operation creates a view on the original array, which is just a way of accesing array data.                          
Thus the original array is not copied in memory.

** When modifying the view, the original array is modified as well:**

In [66]:
a = np.arange(10)

#print (a)

b = a[::2]; b # Only numbers appear in steps of 2

b = 

array([0, 2, 4, 6, 8])