# Indexing & Slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (lists)

In [60]:
import numpy as np
import pandas as pd

from IPython.display import Image 
from IPython.core.display import HTML  # For adding images to this notebook



## Indexing

In [11]:
a = np.arange(10)

print (a) # print them all out, 10 is not shows because Python Indices ALWAYS starts with ZERO

a[0], a[2], a[-1]

[0 1 2 3 4 5 6 7 8 9]


(0, 2, 9)

In [25]:
a = np.diag(np.arange(3))

print (a) # I OVERLY USE PRINT STATEMENTS ON PURPOSE

print (a[1, 1])

a[2, 1] = 10  # Add a '10' to the 3rd row, 2nd column 

a[1, 1] = 4

print (a)

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[[ 0  0  0]
 [ 0  4  0]
 [ 0 10  2]]


## Slicing

In [69]:
a = np.arange(10)
print (a)



# Play around with slicing, what does it do? Use Negative numbers!

# Remove the # in order to view what each print statement does.
#print (a[2:9:3]) # [Start:end:step]
#print (a[:5])
#print (a[2])
#print (a[2:9:1])
#print (a[-2:])

[0 1 2 3 4 5 6 7 8 9]


## This is a cool illustration of Numpy Indexing & Slicing

In [61]:

Image(url= "http://www.scipy-lectures.org/_images/numpy_indexing.png")

# Copies & Views

A slicing operation creates a view on the original array, which is just a way of accesing array data.                          
Thus the original array is not copied in memory.

** When modifying the view, the original array is modified as well:**

In [86]:
a = np.arange(10)

#print (a)

b = a[::2]; b # Only numbers appear in steps of 2

b[0] = 12

#print (b)

# a

a = np.arange(10)

b = a[::2].copy() # Force a copy

b[0] = 12

a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### This behavior can be surprising at first sight... But it allows to save both memory and time.



## **The transpose is a view**   
 
 As a result, a matrix cannot be made a symmetric in-place:

In [88]:
a = np.ones((100, 100))
a += a.T
a

array([[ 2.,  2.,  2., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       ..., 
       [ 3.,  3.,  3., ...,  2.,  2.,  2.],
       [ 3.,  3.,  3., ...,  2.,  2.,  2.],
       [ 3.,  3.,  3., ...,  2.,  2.,  2.]])

In [93]:
Image(url = "http://www.scipy-lectures.org/_images/prime-sieve.png")

Compute prime numbers in 0-99, with a sieve
    - Construct a shape (100,) boolean array *is_prime*, filled with True in the beginning:

In [103]:
is_prime = np.ones((100,), dtype=bool)
#     - Cross out 0 & 1 which are not primes:

is_prime[:2] = 0

#     - For each integeger j starting from 2, cross out its higher multiples:

N_max = int(np.sqrt(len(is_prime)))
for j in range(2, N_max):
    is_prime[2*j::j] = False
    

In [104]:
help(np.nonzero)

Help on function nonzero in module numpy.core.fromnumeric:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order. The corresponding non-zero
    values can be obtained with::
    
        a[nonzero(a)]
    
    To group the indices by element, rather than dimension, use::
    
        transpose(nonzero(a))
    
    The result of this is always a 2-D array, with a row for
    each non-zero element.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened version of the input
        array.
    ndarray.nonzero :
        Equivale

# Fancy Indexing

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called  *fancy indexing*. It creates **copies not view **

Using boolean masks
=================

In [105]:
np.random.seed(3)

a = np.random_int(0, 20, 15)


AttributeError: module 'numpy' has no attribute 'random_int'