# Indexing & Slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (lists)

In [107]:
import numpy as np


from IPython.display import Image 
from IPython.core.display import HTML  # For adding images to this notebook



## Indexing

In [11]:
a = np.arange(10)

print (a) # print them all out, 10 is not shows because Python Indices ALWAYS starts with ZERO

a[0], a[2], a[-1]

[0 1 2 3 4 5 6 7 8 9]


(0, 2, 9)

In [25]:
a = np.diag(np.arange(3))

print (a) # I OVERLY USE PRINT STATEMENTS ON PURPOSE

print (a[1, 1])

a[2, 1] = 10  # Add a '10' to the 3rd row, 2nd column 

a[1, 1] = 4

print (a)

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[[ 0  0  0]
 [ 0  4  0]
 [ 0 10  2]]


## Slicing

In [69]:
a = np.arange(10)
print (a)



# Play around with slicing, what does it do? Use Negative numbers!

# Remove the # in order to view what each print statement does.
#print (a[2:9:3]) # [Start:end:step]
#print (a[:5])
#print (a[2])
#print (a[2:9:1])
#print (a[-2:])

[0 1 2 3 4 5 6 7 8 9]


## This is a cool illustration of Numpy Indexing & Slicing

In [61]:

Image(url= "http://www.scipy-lectures.org/_images/numpy_indexing.png")

# Copies & Views

A slicing operation creates a view on the original array, which is just a way of accesing array data.                          
Thus the original array is not copied in memory.

** When modifying the view, the original array is modified as well:**

In [86]:
a = np.arange(10)

#print (a)

b = a[::2]; b # Only numbers appear in steps of 2

b[0] = 12

#print (b)

# a

a = np.arange(10)

b = a[::2].copy() # Force a copy

b[0] = 12

a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### This behavior can be surprising at first sight... But it allows to save both memory and time.



## **The transpose is a view**   
 
 As a result, a matrix cannot be made a symmetric in-place:

In [88]:
a = np.ones((100, 100))
a += a.T
a

array([[ 2.,  2.,  2., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       [ 2.,  2.,  2., ...,  2.,  2.,  2.],
       ..., 
       [ 3.,  3.,  3., ...,  2.,  2.,  2.],
       [ 3.,  3.,  3., ...,  2.,  2.,  2.],
       [ 3.,  3.,  3., ...,  2.,  2.,  2.]])

In [93]:
Image(url = "http://www.scipy-lectures.org/_images/prime-sieve.png")

Compute prime numbers in 0-99, with a sieve
    - Construct a shape (100,) boolean array *is_prime*, filled with True in the beginning:

In [103]:
is_prime = np.ones((100,), dtype=bool)
#     - Cross out 0 & 1 which are not primes:

is_prime[:2] = 0

#     - For each integeger j starting from 2, cross out its higher multiples:

N_max = int(np.sqrt(len(is_prime)))
for j in range(2, N_max):
    is_prime[2*j::j] = False
    

In [104]:
help(np.nonzero)

Help on function nonzero in module numpy.core.fromnumeric:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order. The corresponding non-zero
    values can be obtained with::
    
        a[nonzero(a)]
    
    To group the indices by element, rather than dimension, use::
    
        transpose(nonzero(a))
    
    The result of this is always a 2-D array, with a row for
    each non-zero element.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened version of the input
        array.
    ndarray.nonzero :
        Equivale

# Masked Arrays :
   ### Masked arrays are arrays that may have missing or invalid entries. The numpy.ma module provides a nearly work-alike replacement for numpy that supports data arrays with masks.
   
   Sometimes the data is incomplete, or tainted by the presence of invalid data. 
   
   https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

# Fancy Indexing

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called  *fancy indexing*. It creates **copies not view **

Using boolean masks
=================

In [118]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)  
# Only use this because you can't be bothered seeing the Depcrating warning, do not use in production code!!!!

In [141]:
np.random.seed(3)

a = np.random.random_integers(0, 20, 15)
# print (a)
(a % 3 == 0)

#mask = (a % 3 == 0)
#extract_from_a = a[mask] # or, a[a%3==0]
#extract_from_a # extract a sub-array with the mask

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False], dtype=bool)

## Indexing with a mask can be very useful to assign a new value to a sub-array:

In [143]:
#a[a % 3 == 0] = -1
#with mask (array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14]))
a
# Result w/o command array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])
# w/o masks

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

## Indexing with an array of integers

In [149]:
a = np.arange(10)
a[::2] += 3 # to avoid having always the same np.arange(10)...
print (a)
a[[2, 5, 1, 8]] # or, a[np.array([2, 5, 1, 8])]

[ 3  1  5  3  7  5  9  7 11  9]


array([ 5,  5,  1, 11])

### Indexing can be done with an array of integers, where the same index is repeated several time:

In [150]:
a[[2, 3, 2, 4, 2]] # note: [2, 3, 2, 4, 2] is a python list

array([5, 3, 5, 7, 5])

### New values can be assigned with this kind of indexing:


In [155]:
a[[9, 7]] = -10

a

array([  3,   1,   5,   3,   7,   5,   9, -10,  11, -10])

In [157]:
a[[2, 3, 2, 4, 2]] += 1
a

array([  3,   1,   7,   5,   9,   5,   9, -10,  11, -10])

### When a new array is created by indexing with an array of integers, the new array has the same shape than the array of integers:

In [167]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
a[idx]

b = np.arange(10)

a = np.arange(12).reshape(3, 4)  # SEE WHAT HAPPENS WHEN YOU TRY TO USE DIFF # to 
a

i = np.array([0, 1, 1, 2])
j = np.array([2, 1, 3, 3])
a[i, j]


array([ 2,  5,  7, 11])

In [169]:
Image(url= "http://www.scipy-lectures.org/_images/numpy_fancy_indexing.png")

### We can even use fancy indexing and broadcasting at the same time:

In [180]:
a = np.arange(12).reshape(3,4)
a

i = np.array([[0, 1], [1, 2]])
a[i, 2]  # same as [i, 2*np.ones((2, 2), dtype=int)]


array([[ 2,  6],
       [ 6, 10]])