I am going to go through this SciPy Lecture.

If you're interested in doing this yourself, you can find it at.

http://www.scipy-lectures.org/intro/numpy/numpy.html

Really appreciate all of the hard-work and effort put by authors

authors: Emmanuelle Gouillart, Didrik Pinte, Gaël Varoquaux, and Pauli Virtanen


In [1]:

import numpy as np 

In [2]:
a = np.array([0, 1, 2, 3])

In [3]:
a # This will tell me what a equals

array([0, 1, 2, 3])

I am getting how to use the Notebook a lot better :)

Why is Numpy useful?

Memory efficient and fast container for numerical operations

1. An Array containing

    . discretized time of an experiment/sumulation
    
    . signal recorded by a measuremnet device
    
    . ....

In [4]:
l = range(1000)

%timeit [i**2 for i in l]

a = np.arange(1000)

%time a**2

1000 loops, best of 3: 746 µs per loop
Wall time: 0 ns


array([     0,      1,      4,      9,     16,     25,     36,     49,
           64,     81,    100,    121,    144,    169,    196,    225,
          256,    289,    324,    361,    400,    441,    484,    529,
          576,    625,    676,    729,    784,    841,    900,    961,
         1024,   1089,   1156,   1225,   1296,   1369,   1444,   1521,
         1600,   1681,   1764,   1849,   1936,   2025,   2116,   2209,
         2304,   2401,   2500,   2601,   2704,   2809,   2916,   3025,
         3136,   3249,   3364,   3481,   3600,   3721,   3844,   3969,
         4096,   4225,   4356,   4489,   4624,   4761,   4900,   5041,
         5184,   5329,   5476,   5625,   5776,   5929,   6084,   6241,
         6400,   6561,   6724,   6889,   7056,   7225,   7396,   7569,
         7744,   7921,   8100,   8281,   8464,   8649,   8836,   9025,
         9216,   9409,   9604,   9801,  10000,  10201,  10404,  10609,
        10816,  11025,  11236,  11449,  11664,  11881,  12100,  12321,
      

# Referencing the Documentation

In [8]:
help(np.array) # useful to read it from here as opposed from the website

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [10]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [11]:
help(np.lookfor)


Help on function lookfor in module numpy.lib.utils:

lookfor(what, module=None, import_modules=True, regenerate=False, output=None)
    Do a keyword search on docstrings.
    
    A list of of objects that matched the search is displayed,
    sorted by relevance. All given keywords need to be found in the
    docstring for it to be returned as a result, but the order does
    not matter.
    
    Parameters
    ----------
    what : str
        String containing words to look for.
    module : str or list, optional
        Name of module(s) whose docstrings to go through.
    import_modules : bool, optional
        Whether to import sub-modules in packages. Default is True.
    regenerate : bool, optional
        Whether to re-generate the docstring cache. Default is False.
    output : file-like, optional
        File-like object to write the output to. If omitted, use a pager.
    
    See Also
    --------
    source, info
    
    Notes
    -----
    Relevance is determined only ro

# Creating Arrays

## 1-D:

In [13]:
a = np.array([0, 1, 2, 3,])
print (a.ndim)
print(a.shape)
len(a)

1
(4,)


4

# 2-D, 3-D, ...:

In [15]:
b = np.array([[0, 1, 2], [3, 4, 5]])

print (b.ndim)
print (b.shape)
print (len(b))

2
(2, 3)
2


In [16]:
c = np.array([[[1], [2]], [[3], [4]]])
print (c)
print (c.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [17]:
a = (np.mat([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 2], [1, 6, 1, 1] ]))

In [18]:
a

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 2],
        [1, 6, 1, 1]])

In [19]:
z = (np.diag([2, 3, 4, 5, 6]))
g =([0, 0, 0, 0, 0])

In [20]:
a = np.array([[1, 1], [2, 2], [3, 3]])

In [21]:
np.insert(a, 6, 6)

array([1, 1, 2, 2, 3, 3, 6])

In [22]:
help(np.append)

Help on function append in module numpy.lib.function_base:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.


In [23]:
b = (np.mat([[0., 0]]))

In [24]:
b = (np.array([[0, 0, 0, 0, 0],
            [2, 0, 0, 0, 0],
            [0, 3, 0, 0, 0],
            [0, 0, 4, 0, 0],
            [0, 0, 0, 5, 0],
            [0, 0, 0, 0, 6]]))

In [25]:
b

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [26]:
help(np.tile)

Help on function tile in module numpy.lib.shape_base:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of rep

In [27]:
c = np.array([[4, 3],[2, 1]])
np.tile(c, (2, 2))

array([[4, 3, 4, 3],
       [2, 1, 2, 1],
       [4, 3, 4, 3],
       [2, 1, 2, 1]])