# Numerical operations on arrays


## Elementwise operations


With Scalars:

In [13]:
import numpy as np # Always import NUMPYY!!!! Because your life depends on it

In [7]:

a = np.array([1, 2, 3, 4])
print (a + 1)

print (2**a)


[2 3 4 5]
[ 2  4  8 16]


All arithmetic operates elementwise:

In [11]:
b = np.ones(4) + 1
print (a - b)

print (a * b)

[-1.  0.  1.  2.]
[ 2.  4.  6.  8.]


In [12]:
a = np.arange(5)

 Array Multiplication is **not** matrix multiplication:
 ======================================================

In [47]:
c = np.ones((3, 3))
print (c * c)

# THIS IS NOT MATRIX MULTIPLCATION
# help(np.dot) # Wanted to know what this function actually does
# Uncomment the above line, so you can see the documentation

d = np.arange(5)


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


# Dot product

I highly suggest you learn the math for dot product, it is really easy.

[Dot_product_wiki](https://en.wikipedia.org/wiki/Dot_product)

# Note: Matrix multiplication:

In [17]:
c.dot(c)

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

# Comparisons

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print (a == b)
print (a > b )


[False  True False  True]
[False False  True False]


# Logical operations:

In [29]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
print (np.logical_or(a, b))
print (np.logical_and(a, b))

[ True  True  True False]
[ True False False False]


**Note**: For arrays: "np.logical_and" AND "np.logical_or" for logical operations, not "and" AND "or"





# Shape mismatches

In [33]:
a
# array([1, 2, 3, 4]) This should be the output (just call the Comparisons code section again)

array([1, 2, 3, 4])

In [34]:
a + np.array([1, 2])

# So this will happen because they do not match. 

# Hence the " operands could not be broadcast together with shapes (4,) (2,) " value error

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Transposition:



In [54]:
a = np.triu(np.ones((3,3)), 1) 

# help(np.triu) #when you see random stuff with np.xyz just read the documentation. :)

#  a good way to understand transposition is : Mirrors & their reflections.
print (a)


print(a.T)

[[ 0.  1.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  1.  0.]]


## Note: Linear Algebra

The sub-module np.linalg implements basic linear algebra, such as [_eigenvalue_](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) decomposition, solving linear systems... However, it is not guaranteed to be compiled efficiently using efficient routines, & thus we recommend to use scipy.linalg [Linear Algebra operations: Scipy.linalg ]("http://www.scipy-lectures.org/intro/scipy.html#scipy-linalg")

## Exercise

 Generate arrays [2**0, 2**1, 2**2, 2**3, 2**4] and a_j = 2^(3*j) - j





In [57]:
#help(np.linalg)


# Basic reductions

Computing Sums:

In [59]:
x = np.array([1, 2, 3, 4])
print (np.sum(x))
print (x.sum())

10
10
